volumes:
  local_pgdata:
  pgadmin-data:

services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgresql-image"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    # The `env_file` tag allows us to declare an environment file
    env_file:
      - .env # The name of your environment file (the one at the repository root)
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
